bbb-record-core: 1:2.3.0-17

diff --git a/bbb-record-core/control/postinst b/bbb-record-core/control/postinst
--- a/bbb-record-core/control/postinst
+++ b/bbb-record-core/control/postinst
@@ -409,8 +409,11 @@ if dpkg -l | grep -q nginx; then
   reloadService nginx
 fi
 
-if ! grep -q xenial /etc/lsb-release; then
-  startService bbb-record-core.timer || echo "bbb-record-core could not be registered or started"
-fi
-
 systemctl daemon-reload
+
+if grep -q xenial /etc/lsb-release; then
+  startService bbb-record-core.timer || echo "bbb-record-core could not be registered or started"
+else
+  startService bbb-rap-starter.service || echo "bbb-rap-starter could not be registered or started"
+  startService bbb-rap-resque-worker.service || echo "bbb-rap-resque-worker could not be registered or started"
+fi
