bbb-record-core: 1:2.5-3

diff --git a/bbb-record-core/control/postinst b/bbb-record-core/control/postinst
--- a/bbb-record-core/control/postinst
+++ b/bbb-record-core/control/postinst
@@ -328,7 +328,6 @@ case "$1" in
 
     chmod +r $TARGET
 
-  if [ ! -f /etc/system-release ]; then
     if ! gem -v | grep -q ^3.; then 
       gem update --system --no-document
       if grep -q bionic /etc/lsb-release; then
@@ -352,14 +351,7 @@ case "$1" in
       echo "## Could not find gem ##"
       exit 1
     fi
-  fi 
-
-  if [ -f /etc/system-release ]; then
-      gem install bundler --no-document
-      cd /usr/local/bigbluebutton/core
-      /usr/local/bin/bundle
-  fi 
-
+    
     # Run recording link fixup/upgrade script
     # Don't abort on failure; users can manually run it later, too
     if id $BBB_USER > /dev/null 2>&1 ; then
@@ -418,13 +410,6 @@ case "$1" in
     else
       echo "Error: FreeSWITCH not installed"
     fi
-
-    # no longer needed in 2.3+
-    if [ -f /usr/share/etherpad-lite/APIKEY.txt ]; then 
-      APIKEY=$(cat /usr/share/etherpad-lite/APIKEY.txt)
-      sed -i "s/ETHERPAD_APIKEY/$APIKEY/g" /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml
-    fi
-
   ;;
   
   *)
@@ -432,20 +417,12 @@ case "$1" in
   ;;
 esac
 
-if which nginx > /dev/null; then
+if dpkg -l | grep -q nginx; then
   reloadService nginx
 fi
 
-systemctl daemon-reload
-
-if [ -f /etc/lsb-release ]; then
-  if grep -q xenial /etc/lsb-release; then
-    startService bbb-record-core.timer || echo "bbb-record-core could not be registered or started"
-  else
-    startService bbb-rap-starter.service || echo "bbb-rap-starter could not be registered or started"
-    startService bbb-rap-resque-worker.service || echo "bbb-rap-resque-worker could not be registered or started"
-  fi
-else
-  startService bbb-rap-starter.service || echo "bbb-rap-starter could not be registered or started"
-  startService bbb-rap-resque-worker.service || echo "bbb-rap-resque-worker could not be registered or started"
+if ! grep -q xenial /etc/lsb-release; then
+  startService bbb-record-core.timer || echo "bbb-record-core could not be registered or started"
 fi
+
+systemctl daemon-reload
