bbb-libreoffice-docker: 1:2.3.0-22

diff --git a/bbb-libreoffice-docker/control/postinst b/bbb-libreoffice-docker/control/postinst
--- a/bbb-libreoffice-docker/control/postinst
+++ b/bbb-libreoffice-docker/control/postinst
@@ -262,10 +262,20 @@ else
   SERVLET_DIR=/usr/share/bbb-web
 fi
 
+# Added for 2.3
+BBB_WEB_ETC_CONFIG=/etc/bigbluebutton/bbb-web.properties
+
+if [ -f /etc/lsb-release ]; then
+  source /etc/lsb-release
+  if [ "$DISTRIB_CODENAME" == "xenial" ]; then
+    unset BBB_WEB_ETC_CONFIG
+  fi
+fi
+
 PROTOCOL=http
 if [ -f $SERVLET_DIR/WEB-INF/classes/bigbluebutton.properties ]; then
-  SERVER_URL=$(cat $SERVLET_DIR/WEB-INF/classes/bigbluebutton.properties | sed -n '/^bigbluebutton.web.serverURL/{s/.*\///;p}')
-  if cat $SERVLET_DIR/WEB-INF/classes/bigbluebutton.properties | grep bigbluebutton.web.serverURL | grep -q https; then
+  SERVER_URL=$(cat $SERVLET_DIR/WEB-INF/classes/bigbluebutton.properties $BBB_WEB_ETC_CONFIG | grep -v '#' | sed -n '/^bigbluebutton.web.serverURL/{s/.*\///;p}' | tail -n 1)
+  if cat $SERVLET_DIR/WEB-INF/classes/bigbluebutton.properties $BBB_WEB_ETC_CONFIG | grep -v '#' | grep ^bigbluebutton.web.serverURL | tail -n 1 | grep -q https; then
     PROTOCOL=https
   fi
 fi
@@ -276,31 +286,36 @@ fi
 ##########################
 
 if ! which docker > /dev/null; then
-	echo "Unable to install bbb-libreoffice-docker -- no docker available"
+	echo "#"
+	echo "# Unable to install bbb-libreoffice-docker -- no docker available"
+	echo "#"
 	exit 0
 fi
 
-if ! docker image inspect bbb-libreoffice > /dev/null 2>&1; then
+if ! docker image inspect bbb-soffice > /dev/null 2>&1; then
 	cd /usr/share/bbb-libreoffice
 	echo "#"
 	echo "# Building bbb-libreoffice docker image"
 	echo "#"
-	docker build -t bbb-libreoffice docker/
+	docker build -t bbb-soffice docker/
 fi
 
-if ! docker network inspect bbb-libreoffice > /dev/null 2>&1; then
-	docker network create bbb-libreoffice -d bridge --opt com.docker.network.bridge.name=br-soffice
+#if ! docker network inspect bbb-libreoffice > /dev/null 2>&1; then
+#	docker network create bbb-libreoffice -d bridge --opt com.docker.network.bridge.name=br-soffice
+#fi
+
+if [ ! -L /usr/share/bbb-libreoffice-conversion/convert.sh ]; then
+	ln -s /usr/share/bbb-libreoffice-conversion/convert-local.sh /usr/share/bbb-libreoffice-conversion/convert.sh
 fi
 
-
-for i in `seq 1 4` ; do
-
-	SOFFICE_WORK_DIR="/var/tmp/soffice_"`printf "%02d\n" ${i}`
-	mkdir -p $SOFFICE_WORK_DIR
-	chown bigbluebutton:bigbluebutton $SOFFICE_WORK_DIR
-
-        systemctl enable bbb-libreoffice@${i}
-        systemctl start bbb-libreoffice@${i}
-done
+#for i in `seq 1 4` ; do
+#
+#	SOFFICE_WORK_DIR="/var/tmp/soffice_"`printf "%02d\n" ${i}`
+#	mkdir -p $SOFFICE_WORK_DIR
+#	chown bigbluebutton:bigbluebutton $SOFFICE_WORK_DIR
+#
+#        systemctl enable bbb-libreoffice@${i}
+#        systemctl start bbb-libreoffice@${i}
+#done
 
 exit 0
